# Generated by Django 2.0.4 on 2018-04-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20180421_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parentid',
            new_name='parent',
        ),
    ]
